
spring:
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5435}/${DB_NAME:byte_bistro}?currentSchema=${DMS_DB_SCHEMA:common}&useSSL=false
    driverClassName: org.postgresql.Driver
    username: "${DMS_DB_USERNAME:postgres}"
    password: "${DMS_DB_PASSWORD:password}"
    dialect: org.hibernate.dialect.PostgreSQL9Dialect
    minPoolSize: 1
    maxPoolSize: 10
server:
  port: 8090
logging:
  level:
    org.springframework.security: TRACE
